{"uid":"10f043bb91eb0333","name":"test_negative_changing_password_user_not_logged","fullName":"tests.test_users.TestUsers#test_negative_changing_password_user_not_logged","historyId":"2c484cb66dc66302baa17f225812f595","time":{"start":1689185539616,"stop":1689185539617,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957272390>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb957272390>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957272390>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957272390>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"feature","value":"Тесты работы с пользователем."},{"name":"story","value":"Тест изменения пароля, без авторизации."},{"name":"tag","value":"test_changing_password_user_not_logged"},{"name":"tag","value":"users_tests(scope='class')"},{"name":"tag","value":"order(1)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_users"},{"name":"subSuite","value":"TestUsers"},{"name":"host","value":"fv-az507-433"},{"name":"thread","value":"2317-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["order(1)","users_tests(scope='class')","test_changing_password_user_not_logged"]},"source":"10f043bb91eb0333.json","parameterValues":[]}