{"uid":"2fbe43c8f4a5c72e","name":"test_negative_tags_not_found","fullName":"tests.test_tags.TestTags#test_negative_tags_not_found","historyId":"4d022a96d12cb447a3eb1179e94870a4","time":{"start":1689185539904,"stop":1689185539905,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e8390>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb9570e8390>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e8390>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e8390>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"feature","value":"Тесты получения списка тегов."},{"name":"story","value":"Тест получения несуществующего тега."},{"name":"tag","value":"test_negative_not_found"},{"name":"tag","value":"tags_tests(scope='class')"},{"name":"tag","value":"order(7)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_tags"},{"name":"subSuite","value":"TestTags"},{"name":"host","value":"fv-az507-433"},{"name":"thread","value":"2317-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_tags"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["tags_tests(scope='class')","test_negative_not_found","order(7)"]},"source":"2fbe43c8f4a5c72e.json","parameterValues":[]}