{"uid":"6239161800139aee","name":"test_unsubscribe_error","fullName":"tests.test_subscription.TestSubscriptions#test_unsubscribe_error","historyId":"6fee54b13e232dc877b90502b117f1b8","time":{"start":1689185539825,"stop":1689185539827,"duration":2},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb9570bdad0>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"feature","value":"Тесты осуществления подписки на пользователя."},{"name":"story","value":"Тест отписки от пользователя."},{"name":"tag","value":"test_unsubscribe_error"},{"name":"tag","value":"subscriptions_tests(scope='class')"},{"name":"tag","value":"order(4)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_subscription"},{"name":"subSuite","value":"TestSubscriptions"},{"name":"host","value":"fv-az507-433"},{"name":"thread","value":"2317-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_subscription"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["subscriptions_tests(scope='class')","test_unsubscribe_error","order(4)"]},"source":"6239161800139aee.json","parameterValues":[]}