{"04c3f5e2ca4d2406a8e07173a8e5d6a3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b161533fd0f6b1ad","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b161533fd0f6b1ad","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d446590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463598,"stop":1689099463601,"duration":3}}]},"3d8c2310dcdf0fa09ef77963288beaae":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4e9845a0875b0478","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4e9845a0875b0478","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3af450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462477,"stop":1689099462478,"duration":1}}]},"c2faddcaa5c781a3d469cb2b110469cc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"7125474be6513c8d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7125474be6513c8d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3aae50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462594,"stop":1689099462597,"duration":3}}]},"12b8b637aa4c2d424e0f293f6e1a6261":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"eae4bef8e478f784","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/eae4bef8e478f784","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d756490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462226,"stop":1689099462229,"duration":3}}]},"b16bab1bf26416be8b02b5b57ad8c2ff":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"8cc43a81d33e6587","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/8cc43a81d33e6587","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d8b0fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464218,"stop":1689099464220,"duration":2}}]},"f7c390d7cc3597e5887f346dfd836f72":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b280fb59696c961c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b280fb59696c961c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d416650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463851,"stop":1689099463854,"duration":3}}]},"bdecc3c5cafe3f9ebebb59a04f24e6b8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d0f134bc9783cb4e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/d0f134bc9783cb4e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d51f550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461860,"stop":1689099461862,"duration":2}}]},"0c41c7377d01db82d03d4698b1ca5133":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"10225744bc2101ba","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/10225744bc2101ba","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4928d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461239,"stop":1689099461241,"duration":2}}]},"320ac8f8d0d99852391a7b3854d421cf":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"388f3a4618c37520","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/388f3a4618c37520","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d53e590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464454,"stop":1689099464456,"duration":2}}]},"c10642315bdc1772ce7d3e4eca2b01fb":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"c09c410dff25a4d9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c09c410dff25a4d9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d478fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462965,"stop":1689099462967,"duration":2}}]},"597ae4f0152cb7f437f4ec96794fa1d8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3fff66743086d996","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3fff66743086d996","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d25e610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465337,"stop":1689099465339,"duration":2}}]},"4d8270dc613966068cdf37650e0c3f1b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"45ace8b2687d9b7c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/45ace8b2687d9b7c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4ff9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461614,"stop":1689099461615,"duration":1}}]},"b222afed1bbb12d08851e139dfd328c1":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"149dd58dc9520245","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/149dd58dc9520245","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2ddf10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463478,"stop":1689099463480,"duration":2}}]},"b834b96496eaf5ec890561b9bb9c2b13":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e01f02cf59646b0e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e01f02cf59646b0e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d32f8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463717,"stop":1689099463720,"duration":3}}]},"ed973a1c6247e086e2ca7b67f8861f99":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f37dd23307146b58","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f37dd23307146b58","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9eb712d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099460947,"stop":1689099460949,"duration":2}}]},"136fdf1cbe0628ab86cd5878f203a373":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3311017f57eae875","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3311017f57eae875","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d199690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465594,"stop":1689099465595,"duration":1}}]},"c2adbfbbd491c2597b0fda673439e511":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e81ec34786e32f8a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e81ec34786e32f8a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d744c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461745,"stop":1689099461746,"duration":1}}]},"2c484cb66dc66302baa17f225812f595":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"a5b8613002237dde","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a5b8613002237dde","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d7de490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462109,"stop":1689099462111,"duration":2}}]},"614551ca7970e22e71d92ff29a709595":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"51a14ba5304f1ade","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/51a14ba5304f1ade","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d29b390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465712,"stop":1689099465713,"duration":1}}]},"5d1ba22e143d84f83c3ace0980e350d4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f65d34a6299a2366","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f65d34a6299a2366","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d1f9350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465452,"stop":1689099465455,"duration":3}}]},"f27bc5b997e6f4038ef2c5a6bf35e262":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"12f53ebabc9f87e9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/12f53ebabc9f87e9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d442dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462849,"stop":1689099462850,"duration":1}}]},"07cd58bcb29a137195fe207cd8cf4156":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"649f41824447023d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/649f41824447023d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d464f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464085,"stop":1689099464088,"duration":3}}]},"8bb43b26ad1d96a78a3961b3077bee32":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e16b4c19c666b053","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e16b4c19c666b053","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d6575d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461124,"stop":1689099461126,"duration":2}}]},"68a2c7a9203c112407f758b4272d49a6":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"84768b3fb43bf72e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/84768b3fb43bf72e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d226550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465963,"stop":1689099465965,"duration":2}}]},"8ff593a56c4b3218c5c7be797b996bb4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"918ced5319770fca","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/918ced5319770fca","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4d9f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461492,"stop":1689099461495,"duration":3}}]},"4df2eef17fb723554959c68ea1793cf3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b6deb582fcab0814","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b6deb582fcab0814","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d41bdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462731,"stop":1689099462734,"duration":3}}]},"6bbf5dca39d77801411a2696df165a23":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"467d429b7bba4278","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/467d429b7bba4278","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d28cd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463219,"stop":1689099463222,"duration":3}}]},"7c85eb922c681fbdd70cc78d116d1dc4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3ada954aabb7fab","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3ada954aabb7fab","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3ab8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463102,"stop":1689099463104,"duration":2}}]},"6fee54b13e232dc877b90502b117f1b8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"390e4d12932519c2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/390e4d12932519c2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2a0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464961,"stop":1689099464963,"duration":2}}]},"18f81c631f68676ddc55a3e4d49da9c7":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"852fb49ed7e5fe3f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/852fb49ed7e5fe3f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d1f5e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465218,"stop":1689099465221,"duration":3}}]},"73faf4ff75facc1ada4c99bd363df620":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"7d50763b1f2b36f1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7d50763b1f2b36f1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2c0290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463338,"stop":1689099463341,"duration":3}}]},"c3e68df8cccb43ad311c77d8989df80c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1c16db6f433ceab5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/1c16db6f433ceab5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d676f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461373,"stop":1689099461377,"duration":4}}]},"b1fc92bb811b4a1bcef076e074cd3369":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f67d4122ef73410a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f67d4122ef73410a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d416850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464587,"stop":1689099464590,"duration":3}}]},"19ffdcefa3b9df970185d80f63b32d70":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"5f0b1775022936dd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/5f0b1775022936dd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2f2810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464706,"stop":1689099464708,"duration":2}}]},"6216d5120ac0239aab4d58de3351c7c5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"47510904f8fd8eb1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/47510904f8fd8eb1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d335590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463969,"stop":1689099463970,"duration":1}}]},"b7d9874195a95979ffa8a88c67ae5aba":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4fe004f44616e07e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4fe004f44616e07e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d248b90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465079,"stop":1689099465082,"duration":3}}]},"f2280457ffd433e4572bf538c4b03a78":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2dcd31a4f9e0ecf0","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2dcd31a4f9e0ecf0","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d689350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464333,"stop":1689099464337,"duration":4}}]},"b326a8ce65cd93d89129056abf81fa8b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e97c5b3c3a03a4c4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e97c5b3c3a03a4c4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3c0410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462345,"stop":1689099462348,"duration":3}}]},"73d6b215df134dbc7235023eaa36add9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"a2451ac6e0d5e76f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a2451ac6e0d5e76f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d6d3c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461976,"stop":1689099461979,"duration":3}}]},"4414e0858f9bd3714e43755837dfe2fc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"8efa1ac43c542b6a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/8efa1ac43c542b6a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d560b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464843,"stop":1689099464846,"duration":3}}]},"4d022a96d12cb447a3eb1179e94870a4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4415c3c9718e11fc","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4415c3c9718e11fc","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d7e3850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099466079,"stop":1689099466081,"duration":2}}]},"adf9e8f1ccaef70993531bf3a2a95b28":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"19e0e923a731dff1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/19e0e923a731dff1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d83ef90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465828,"stop":1689099465830,"duration":2}}]}}