{"04c3f5e2ca4d2406a8e07173a8e5d6a3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"cdb9ede6ea0ae514","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/cdb9ede6ea0ae514","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3808cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234396,"stop":1689148234399,"duration":3}}]},"3d8c2310dcdf0fa09ef77963288beaae":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f7129c7cccd89173","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/f7129c7cccd89173","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e375cd90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233306,"stop":1689148233308,"duration":2}}]},"c2faddcaa5c781a3d469cb2b110469cc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"6511d0d279163ab7","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/6511d0d279163ab7","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3777950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233420,"stop":1689148233423,"duration":3}}]},"12b8b637aa4c2d424e0f293f6e1a6261":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e45d1b730f88362","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/e45d1b730f88362","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3701c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233059,"stop":1689148233062,"duration":3}}]},"f7c390d7cc3597e5887f346dfd836f72":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3371489eb5369fbe","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/3371489eb5369fbe","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e34f1a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234644,"stop":1689148234647,"duration":3}}]},"b16bab1bf26416be8b02b5b57ad8c2ff":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1ea6731913de9fca","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/1ea6731913de9fca","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a92890>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235005,"stop":1689148235007,"duration":2}}]},"0c41c7377d01db82d03d4698b1ca5133":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"bcd668634680021e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/bcd668634680021e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e37c2390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232092,"stop":1689148232093,"duration":1}}]},"bdecc3c5cafe3f9ebebb59a04f24e6b8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"329e14f825090c4a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/329e14f825090c4a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3c60fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232703,"stop":1689148232705,"duration":2}}]},"320ac8f8d0d99852391a7b3854d421cf":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"7c26ed13953c2b22","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/7c26ed13953c2b22","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e379bb10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235235,"stop":1689148235237,"duration":2}}]},"c10642315bdc1772ce7d3e4eca2b01fb":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"aadddb26f8c4fe0b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/aadddb26f8c4fe0b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e35e4750>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233784,"stop":1689148233785,"duration":1}}]},"597ae4f0152cb7f437f4ec96794fa1d8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2d0ac3b0d05c5fe3","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/2d0ac3b0d05c5fe3","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3b13e50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236108,"stop":1689148236110,"duration":2}}]},"b222afed1bbb12d08851e139dfd328c1":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"df9289d6c020182","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/df9289d6c020182","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3683690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234280,"stop":1689148234281,"duration":1}}]},"4d8270dc613966068cdf37650e0c3f1b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"ddf979afe4c2bd83","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/ddf979afe4c2bd83","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e386b710>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232456,"stop":1689148232458,"duration":2}}]},"b834b96496eaf5ec890561b9bb9c2b13":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"6c51c1b92f30d75c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/6c51c1b92f30d75c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e34e24d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234513,"stop":1689148234516,"duration":3}}]},"ed973a1c6247e086e2ca7b67f8861f99":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"31b36fc1688ec45e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/31b36fc1688ec45e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e40d9950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148231812,"stop":1689148231815,"duration":3}}]},"136fdf1cbe0628ab86cd5878f203a373":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2f34396cf748f6b9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/2f34396cf748f6b9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e345e310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236359,"stop":1689148236360,"duration":1}}]},"2c484cb66dc66302baa17f225812f595":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d3da91d943eb66cf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/d3da91d943eb66cf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a99050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232946,"stop":1689148232948,"duration":2}}]},"c2adbfbbd491c2597b0fda673439e511":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f99027b6663aa1e5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/f99027b6663aa1e5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a92190>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232586,"stop":1689148232588,"duration":2}}]},"614551ca7970e22e71d92ff29a709595":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"c558da68de89bdf2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/c558da68de89bdf2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a92790>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236477,"stop":1689148236478,"duration":1}}]},"f27bc5b997e6f4038ef2c5a6bf35e262":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f77ef079baaac9ad","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/f77ef079baaac9ad","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e35cb610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233670,"stop":1689148233671,"duration":1}}]},"5d1ba22e143d84f83c3ace0980e350d4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e0516140c96f405b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/e0516140c96f405b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e352b550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236223,"stop":1689148236225,"duration":2}}]},"07cd58bcb29a137195fe207cd8cf4156":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"58d58f8948d5c85","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/58d58f8948d5c85","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3536b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234874,"stop":1689148234877,"duration":3}}]},"8bb43b26ad1d96a78a3961b3077bee32":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d7d4f8d1534c21b2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/d7d4f8d1534c21b2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3995f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148231979,"stop":1689148231981,"duration":2}}]},"68a2c7a9203c112407f758b4272d49a6":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4a7ee63f899a4d30","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/4a7ee63f899a4d30","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a9ba90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236728,"stop":1689148236730,"duration":2}}]},"8ff593a56c4b3218c5c7be797b996bb4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f5714b2a0f6cfe41","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/f5714b2a0f6cfe41","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a08c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232341,"stop":1689148232344,"duration":3}}]},"4df2eef17fb723554959c68ea1793cf3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4b2655beeae4ba05","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/4b2655beeae4ba05","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3876010>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233554,"stop":1689148233556,"duration":2}}]},"6bbf5dca39d77801411a2696df165a23":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"15bd3cf721e66b3d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/15bd3cf721e66b3d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3625510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234031,"stop":1689148234034,"duration":3}}]},"7c85eb922c681fbdd70cc78d116d1dc4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e9b42acbadec77b7","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/e9b42acbadec77b7","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3608fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233917,"stop":1689148233918,"duration":1}}]},"6fee54b13e232dc877b90502b117f1b8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"525dc7216632fa32","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/525dc7216632fa32","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e34bf150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235739,"stop":1689148235740,"duration":1}}]},"18f81c631f68676ddc55a3e4d49da9c7":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"ff5b5be95e3f6c01","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/ff5b5be95e3f6c01","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3504250>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235991,"stop":1689148235994,"duration":3}}]},"73faf4ff75facc1ada4c99bd363df620":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"beb98d8e43bd7a73","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/beb98d8e43bd7a73","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3668c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234147,"stop":1689148234150,"duration":3}}]},"c3e68df8cccb43ad311c77d8989df80c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"eb55ed01cf75304b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/eb55ed01cf75304b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3a56c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232224,"stop":1689148232227,"duration":3}}]},"b1fc92bb811b4a1bcef076e074cd3369":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"db0ba9c234eda110","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/db0ba9c234eda110","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e35e7c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235366,"stop":1689148235369,"duration":3}}]},"19ffdcefa3b9df970185d80f63b32d70":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2ab813a6ec674324","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/2ab813a6ec674324","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e37ea850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235483,"stop":1689148235485,"duration":2}}]},"f2280457ffd433e4572bf538c4b03a78":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"20cfe06e9ca5533e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/20cfe06e9ca5533e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3dd47d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235118,"stop":1689148235121,"duration":3}}]},"b326a8ce65cd93d89129056abf81fa8b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"fcee77f95c5fbd14","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/fcee77f95c5fbd14","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3745750>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148233176,"stop":1689148233179,"duration":3}}]},"6216d5120ac0239aab4d58de3351c7c5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1f8c790a8a338308","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/1f8c790a8a338308","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3686910>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148234761,"stop":1689148234762,"duration":1}}]},"b7d9874195a95979ffa8a88c67ae5aba":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"35928555a7c8e976","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/35928555a7c8e976","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e358d390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235853,"stop":1689148235856,"duration":3}}]},"adf9e8f1ccaef70993531bf3a2a95b28":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d2e492a622997b73","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/d2e492a622997b73","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3544bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236594,"stop":1689148236595,"duration":1}}]},"4414e0858f9bd3714e43755837dfe2fc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1b7e79b3ab101eac","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/1b7e79b3ab101eac","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e3652c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148235621,"stop":1689148235624,"duration":3}}]},"73d6b215df134dbc7235023eaa36add9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b3563417f725e580","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/b3563417f725e580","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e36b3050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148232817,"stop":1689148232820,"duration":3}}]},"4d022a96d12cb447a3eb1179e94870a4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"5d979ecdd956341a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/15//#testresult/5d979ecdd956341a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33e34947d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689148236844,"stop":1689148236845,"duration":1}}]}}