{"04c3f5e2ca4d2406a8e07173a8e5d6a3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"295577f2c334eb26","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/295577f2c334eb26","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95729ca90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539723,"stop":1689185539727,"duration":4}}]},"3d8c2310dcdf0fa09ef77963288beaae":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"8b88c6e4d03bf478","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/8b88c6e4d03bf478","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572850d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539643,"stop":1689185539645,"duration":2}}]},"c2faddcaa5c781a3d469cb2b110469cc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"377ab978ab151b37","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/377ab978ab151b37","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957280bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539651,"stop":1689185539655,"duration":4}}]},"12b8b637aa4c2d424e0f293f6e1a6261":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"804a61227d292edf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/804a61227d292edf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95727a5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539624,"stop":1689185539627,"duration":3}}]},"b16bab1bf26416be8b02b5b57ad8c2ff":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"88489a4008579b1e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/88489a4008579b1e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572ac290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539772,"stop":1689185539773,"duration":1}}]},"f7c390d7cc3597e5887f346dfd836f72":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"14d473b72f0be955","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/14d473b72f0be955","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95729ffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539743,"stop":1689185539747,"duration":4}}]},"0c41c7377d01db82d03d4698b1ca5133":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3090f00e322148e3","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/3090f00e322148e3","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957203710>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539551,"stop":1689185539554,"duration":3}}]},"bdecc3c5cafe3f9ebebb59a04f24e6b8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"fd70c6b6e6237d2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/fd70c6b6e6237d2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95725ef10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539598,"stop":1689185539599,"duration":1}}]},"320ac8f8d0d99852391a7b3854d421cf":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"34003a82c1b0edf6","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/34003a82c1b0edf6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572a5050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539790,"stop":1689185539791,"duration":1}}]},"c10642315bdc1772ce7d3e4eca2b01fb":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4832b0b4898adf61","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/4832b0b4898adf61","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95727aa90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539680,"stop":1689185539681,"duration":1}}]},"597ae4f0152cb7f437f4ec96794fa1d8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"7e146181bc6c75bf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/7e146181bc6c75bf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570eaa90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539853,"stop":1689185539854,"duration":1}}]},"4d8270dc613966068cdf37650e0c3f1b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"cc24086b12ff93aa","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/cc24086b12ff93aa","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957202dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539581,"stop":1689185539582,"duration":1}}]},"b222afed1bbb12d08851e139dfd328c1":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"12a02595af37c44c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/12a02595af37c44c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957279810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539715,"stop":1689185539717,"duration":2}}]},"b834b96496eaf5ec890561b9bb9c2b13":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e96a1c60bdc317b9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/e96a1c60bdc317b9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9574b14d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539733,"stop":1689185539737,"duration":4}}]},"136fdf1cbe0628ab86cd5878f203a373":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"66570e5f19124ddb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/66570e5f19124ddb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570f9050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539870,"stop":1689185539872,"duration":2}}]},"ed973a1c6247e086e2ca7b67f8861f99":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"67d341bb1bd97e16","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/67d341bb1bd97e16","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb958240c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539504,"stop":1689185539507,"duration":3}}]},"c2adbfbbd491c2597b0fda673439e511":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f3ede33e732bef7a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/f3ede33e732bef7a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957264f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539589,"stop":1689185539591,"duration":2}}]},"2c484cb66dc66302baa17f225812f595":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"10f043bb91eb0333","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/10f043bb91eb0333","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957272390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539616,"stop":1689185539617,"duration":1}}]},"614551ca7970e22e71d92ff29a709595":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"32b0180766b843c6","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/32b0180766b843c6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570f1c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539879,"stop":1689185539880,"duration":1}}]},"f27bc5b997e6f4038ef2c5a6bf35e262":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1a2c42cf99de9ca8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/1a2c42cf99de9ca8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957286050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539672,"stop":1689185539673,"duration":1}}]},"5d1ba22e143d84f83c3ace0980e350d4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"a36dac0cb7ef4f96","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/a36dac0cb7ef4f96","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e26d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539861,"stop":1689185539864,"duration":3}}]},"07cd58bcb29a137195fe207cd8cf4156":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b5cada095701f3c7","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/b5cada095701f3c7","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572aa2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539762,"stop":1689185539765,"duration":3}}]},"8bb43b26ad1d96a78a3961b3077bee32":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3926c69433be3f08","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/3926c69433be3f08","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957234f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539543,"stop":1689185539545,"duration":2}}]},"68a2c7a9203c112407f758b4272d49a6":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"bf45bd7ba0d165e8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/bf45bd7ba0d165e8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570f9a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539896,"stop":1689185539898,"duration":2}}]},"8ff593a56c4b3218c5c7be797b996bb4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"867b042d5027ddd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/867b042d5027ddd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95725de90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539571,"stop":1689185539574,"duration":3}}]},"6bbf5dca39d77801411a2696df165a23":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4bd2192c4d0570b6","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/4bd2192c4d0570b6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957270d50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539695,"stop":1689185539699,"duration":4}}]},"4df2eef17fb723554959c68ea1793cf3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"976d62db9b15671","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/976d62db9b15671","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95728fa50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539661,"stop":1689185539664,"duration":3}}]},"7c85eb922c681fbdd70cc78d116d1dc4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d3025f074cd14be8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/d3025f074cd14be8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95727bb10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539687,"stop":1689185539689,"duration":2}}]},"6fee54b13e232dc877b90502b117f1b8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"6239161800139aee","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/6239161800139aee","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539825,"stop":1689185539827,"duration":2}}]},"18f81c631f68676ddc55a3e4d49da9c7":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"a937cb01a3ac5be4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/a937cb01a3ac5be4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570ce010>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539843,"stop":1689185539846,"duration":3}}]},"73faf4ff75facc1ada4c99bd363df620":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"8c6c9079a9f19aec","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/8c6c9079a9f19aec","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957240450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539705,"stop":1689185539709,"duration":4}}]},"c3e68df8cccb43ad311c77d8989df80c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"797b3669c2987ee1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/797b3669c2987ee1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957240510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539560,"stop":1689185539564,"duration":4}}]},"b1fc92bb811b4a1bcef076e074cd3369":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d0798ab86575ec7b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/d0798ab86575ec7b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bedd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539798,"stop":1689185539801,"duration":3}}]},"19ffdcefa3b9df970185d80f63b32d70":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"5a049b09dfb90a21","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/5a049b09dfb90a21","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572b3510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539807,"stop":1689185539809,"duration":2}}]},"f2280457ffd433e4572bf538c4b03a78":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e8cef8937f229c7d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/e8cef8937f229c7d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572b07d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539780,"stop":1689185539783,"duration":3}}]},"b326a8ce65cd93d89129056abf81fa8b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"892b1a2a1efb54d9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/892b1a2a1efb54d9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95725c610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539634,"stop":1689185539637,"duration":3}}]},"b7d9874195a95979ffa8a88c67ae5aba":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b7185f7a6c8e0f64","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/b7185f7a6c8e0f64","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570dffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539833,"stop":1689185539836,"duration":3}}]},"6216d5120ac0239aab4d58de3351c7c5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"69902de2a2edec3f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/69902de2a2edec3f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572a5e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539753,"stop":1689185539755,"duration":2}}]},"4d022a96d12cb447a3eb1179e94870a4":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2fbe43c8f4a5c72e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/2fbe43c8f4a5c72e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e8390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539904,"stop":1689185539905,"duration":1}}]},"adf9e8f1ccaef70993531bf3a2a95b28":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"c8d0941cd4708c8c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/c8d0941cd4708c8c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570ff5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539887,"stop":1689185539888,"duration":1}}]},"73d6b215df134dbc7235023eaa36add9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e1ce6f10dff785f6","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/e1ce6f10dff785f6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572701d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539606,"stop":1689185539609,"duration":3}}]},"4414e0858f9bd3714e43755837dfe2fc":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"25a1ef88d22ec64e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/19//#testresult/25a1ef88d22ec64e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570cd590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689185539815,"stop":1689185539819,"duration":4}}]}}