{"uid":"322822a2a9c2a78f","name":"test_negative_add_recipe_favorites_user_not_logged","fullName":"tests.test_favourites.TestRecipeFavorites#test_negative_add_recipe_favorites_user_not_logged","historyId":"6216d5120ac0239aab4d58de3351c7c5","time":{"start":1689189538123,"stop":1689189538124,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6f010>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb31fa6f010>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6f010>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6f010>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"story","value":"Тест добавления рецептов в избранное, без авторизации"},{"name":"feature","value":"Тест добавления рецептов в избранное."},{"name":"tag","value":"test_negative_add_recipe_favorites_user_not_logged"},{"name":"tag","value":"recipe_favorites_tests(scope='class')"},{"name":"tag","value":"order(3)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_favourites"},{"name":"subSuite","value":"TestRecipeFavorites"},{"name":"host","value":"fv-az309-816"},{"name":"thread","value":"2346-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_favourites"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["order(3)","test_negative_add_recipe_favorites_user_not_logged","recipe_favorites_tests(scope='class')"]},"source":"322822a2a9c2a78f.json","parameterValues":[]}