{"uid":"c6fa8b07053fda58","name":"test_tags_list","fullName":"tests.test_tags.TestTags#test_tags_list","historyId":"68a2c7a9203c112407f758b4272d49a6","time":{"start":1689189538232,"stop":1689189541236,"duration":3004},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))","steps":[],"attachments":[{"uid":"873fbf21f9d88477","name":"log","source":"873fbf21f9d88477.txt","type":"text/plain","size":971}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"Тест получения списка тегов."},{"name":"feature","value":"Тесты получения списка тегов."},{"name":"tag","value":"test_tags_list"},{"name":"tag","value":"tags_tests(scope='class')"},{"name":"tag","value":"order(7)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_tags"},{"name":"subSuite","value":"TestTags"},{"name":"host","value":"fv-az309-816"},{"name":"thread","value":"2346-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_tags"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["tags_tests(scope='class')","test_tags_list","order(7)"]},"source":"c6fa8b07053fda58.json","parameterValues":[]}