{"uid":"ca356e4f34485e55","name":"test_get_subscriptions_user_not_logged","fullName":"tests.test_subscription.TestSubscriptions#test_get_subscriptions_user_not_logged","historyId":"19ffdcefa3b9df970185d80f63b32d70","time":{"start":1689189538164,"stop":1689189538165,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa81f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb31fa81f10>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa81f10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa81f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"feature","value":"Тесты осуществления подписки на пользователя."},{"name":"story","value":"Тест получения подписок пользователя без авторизации."},{"name":"tag","value":"test_get_subscriptions_user_not_logged"},{"name":"tag","value":"subscriptions_tests(scope='class')"},{"name":"tag","value":"order(4)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_subscription"},{"name":"subSuite","value":"TestSubscriptions"},{"name":"host","value":"fv-az309-816"},{"name":"thread","value":"2346-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_subscription"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["subscriptions_tests(scope='class')","test_get_subscriptions_user_not_logged","order(4)"]},"source":"ca356e4f34485e55.json","parameterValues":[]}