{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb32027cd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_users_list","uid":"57ff0f2061891012","parentUid":"7176a570f3c9625c74666a73a6662255","status":"broken","time":{"start":1689189537910,"stop":1689189537912,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7176a570f3c9625c74666a73a6662255"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f9fe1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_user_registration","uid":"20362f5682bae84a","parentUid":"4d0e340e1bca1677e640ddbb967005f5","status":"broken","time":{"start":1689189537960,"stop":1689189537962,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"test_negative_user_registration","uid":"36e4478cc4be7cee","parentUid":"4d0e340e1bca1677e640ddbb967005f5","status":"broken","time":{"start":1689189537967,"stop":1689189537969,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4d0e340e1bca1677e640ddbb967005f5"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa05690>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_user_profile","uid":"f36fae86a48ca2a","parentUid":"ac178564286451a0752861afb627e1be","status":"broken","time":{"start":1689189537974,"stop":1689189537977,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ac178564286451a0752861afb627e1be"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb32100afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_nagative_get_user_profile_object_not_found","uid":"dcdf5bd5fd97412b","parentUid":"7d5610658708036d2dbd16ef26f0ae74","status":"broken","time":{"start":1689189537982,"stop":1689189537985,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7d5610658708036d2dbd16ef26f0ae74"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f9ff2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_get_user_profile_not_logged","uid":"7daba21ddcfb7639","parentUid":"46f6baf9ad8f2a444e16de59ba9a29a4","status":"broken","time":{"start":1689189537990,"stop":1689189537991,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"46f6baf9ad8f2a444e16de59ba9a29a4"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa2e290>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_current_user","uid":"f2a5b99186d67057","parentUid":"b101833351270941764863c9e24d35ee","status":"broken","time":{"start":1689189537996,"stop":1689189537997,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b101833351270941764863c9e24d35ee"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa25a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_get_current_user","uid":"8b574a418a1d8c07","parentUid":"de56ef35e331917e2c13d622fee0a718","status":"broken","time":{"start":1689189538003,"stop":1689189538004,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"de56ef35e331917e2c13d622fee0a718"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa394d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_changing_password","uid":"8a90e8d3768055ad","parentUid":"a4ff371d7da70701bf6b8960d4326c39","status":"broken","time":{"start":1689189538009,"stop":1689189538012,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a4ff371d7da70701bf6b8960d4326c39"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa3b790>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_changing_password_user_not_logged","uid":"54f35b3f7ac90f40","parentUid":"f65fce3e10ca44757aba0b4d5c9cb7af","status":"broken","time":{"start":1689189538017,"stop":1689189538018,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"f65fce3e10ca44757aba0b4d5c9cb7af"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa3f9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_changing_password_validation_error","uid":"8e70bf97e7209142","parentUid":"880893de609f5f9824ceba251ea904a6","status":"broken","time":{"start":1689189538023,"stop":1689189538025,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"880893de609f5f9824ceba251ea904a6"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa2e510>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_token","uid":"6805775aae0328ce","parentUid":"420f98ee921676f1a6dd001d044a2d0c","status":"broken","time":{"start":1689189538031,"stop":1689189538033,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"420f98ee921676f1a6dd001d044a2d0c"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa4e3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_delete_token_user_not_logged","uid":"9241be1b1e10cbf9","parentUid":"67bc8a2cdb5ac601fae4595c9edda7d2","status":"broken","time":{"start":1689189538038,"stop":1689189538039,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"67bc8a2cdb5ac601fae4595c9edda7d2"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa4a110>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_create_recipe","uid":"9a0675a5bbd27831","parentUid":"0cde91992d8676be26ec5d57b8bf4511","status":"broken","time":{"start":1689189538044,"stop":1689189538047,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0cde91992d8676be26ec5d57b8bf4511"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa5cd90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_create_recipe_validation_error","uid":"cd7e5b86ba80ddcf","parentUid":"a6fc45d353a49224cc13ae232c6ab0f1","status":"broken","time":{"start":1689189538052,"stop":1689189538054,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a6fc45d353a49224cc13ae232c6ab0f1"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa4ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_create_recipe_user_not_logged","uid":"ba79b7aaeca149ac","parentUid":"8ac405ef8a241c407cc73a9c1cc34a62","status":"broken","time":{"start":1689189538060,"stop":1689189538062,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"8ac405ef8a241c407cc73a9c1cc34a62"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa3e850>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_recipe","uid":"f83000747bf431e2","parentUid":"3a8fe633f7b02d74c9da90343eea69ce","status":"broken","time":{"start":1689189538067,"stop":1689189538068,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3a8fe633f7b02d74c9da90343eea69ce"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa3f750>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_recipes_list","uid":"1050c777b4975c4b","parentUid":"0c8c5457c1b9419ed29d80d780410995","status":"broken","time":{"start":1689189538073,"stop":1689189538074,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0c8c5457c1b9419ed29d80d780410995"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa3b6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_patch_recipe","uid":"df8656270664188","parentUid":"35af18004a950ac75e3d91adada3866f","status":"broken","time":{"start":1689189538079,"stop":1689189538082,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"35af18004a950ac75e3d91adada3866f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa54e50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_patch_recipe_validation_error","uid":"462b2597a8ef8f93","parentUid":"b171aed1852258864f817c855665c0ae","status":"broken","time":{"start":1689189538086,"stop":1689189538089,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b171aed1852258864f817c855665c0ae"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa3f9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_patch_recipe_user_not_logged","uid":"88bc2abaa760fbac","parentUid":"d57426705496f443dba180e627b346a4","status":"broken","time":{"start":1689189538094,"stop":1689189538095,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"d57426705496f443dba180e627b346a4"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa65c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_recipe","uid":"8c69a44ae5661379","parentUid":"bb697c662233ebd167064da23f5c30f0","status":"broken","time":{"start":1689189538100,"stop":1689189538103,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"bb697c662233ebd167064da23f5c30f0"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa2d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_recipe_favorites","uid":"1acbb3b79f1fe2f2","parentUid":"4b3c9b65627c2e18d56e0e8ed1b1124f","status":"broken","time":{"start":1689189538108,"stop":1689189538110,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4b3c9b65627c2e18d56e0e8ed1b1124f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6d190>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_add_recipe_favorites_validation_error","uid":"cd8c11a700205d7c","parentUid":"ff67010e5fa74cc2c42838c5dfefdd0b","status":"broken","time":{"start":1689189538115,"stop":1689189538118,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ff67010e5fa74cc2c42838c5dfefdd0b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6f010>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_add_recipe_favorites_user_not_logged","uid":"322822a2a9c2a78f","parentUid":"691d32b650614477c86b0d550aa02ad9","status":"broken","time":{"start":1689189538123,"stop":1689189538124,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"691d32b650614477c86b0d550aa02ad9"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa73450>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_recipe_delete_favorites","uid":"566f01f77553bb4b","parentUid":"b98a930f501b948d516cb43ce97deff1","status":"broken","time":{"start":1689189538129,"stop":1689189538131,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b98a930f501b948d516cb43ce97deff1"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa75410>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_recipe_delete_favorites_user_not_logged","uid":"5f8ff9bb40c9aa9a","parentUid":"d6dc34355efba8d9685e0804f3b9b2bc","status":"broken","time":{"start":1689189538137,"stop":1689189538138,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"d6dc34355efba8d9685e0804f3b9b2bc"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa79950>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_subscribe_to_user","uid":"78812c34bbcfa209","parentUid":"3b0b21c4219a62ec1407ec3c389703fc","status":"broken","time":{"start":1689189538143,"stop":1689189538145,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3b0b21c4219a62ec1407ec3c389703fc"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6e010>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_subscribe_to_user_not_logged","uid":"d466e4adec035fa1","parentUid":"2861a5022d698043de75fdc8a8bc265f","status":"broken","time":{"start":1689189538150,"stop":1689189538152,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"2861a5022d698043de75fdc8a8bc265f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa83f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_subscriptions","uid":"bd7669795234bb98","parentUid":"c96b8dbdafc4a76e3732d73758348e6e","status":"broken","time":{"start":1689189538156,"stop":1689189538159,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c96b8dbdafc4a76e3732d73758348e6e"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa81f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_subscriptions_user_not_logged","uid":"ca356e4f34485e55","parentUid":"ceda069c8e908f98d090e410c2a8fff6","status":"broken","time":{"start":1689189538164,"stop":1689189538165,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ceda069c8e908f98d090e410c2a8fff6"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f88e810>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_unsubscribe_to_user","uid":"5c445ee9a46427ba","parentUid":"4aa7d8504f2aee1d04348e8c37a1cadf","status":"broken","time":{"start":1689189538170,"stop":1689189538173,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4aa7d8504f2aee1d04348e8c37a1cadf"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa6c210>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_unsubscribe_error","uid":"cd15d46adb5c1698","parentUid":"4530d643a564123950a7b157224e482e","status":"broken","time":{"start":1689189538178,"stop":1689189538179,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4530d643a564123950a7b157224e482e"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8a5210>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_shopping_cart","uid":"4c9afbe8ab76083e","parentUid":"0473b35431a351994d6c543e2cd2622b","status":"broken","time":{"start":1689189538184,"stop":1689189538186,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0473b35431a351994d6c543e2cd2622b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f89bf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_download_shopping_cart","uid":"30c072a06f4d4959","parentUid":"be568dcf8f1287f958ad4b9d548a4521","status":"broken","time":{"start":1689189538192,"stop":1689189538194,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"be568dcf8f1287f958ad4b9d548a4521"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8afc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_download_shopping_cart_not_logged","uid":"8077b44e4908f379","parentUid":"2db14de36cc6e22f7cde229aad61c276","status":"broken","time":{"start":1689189538199,"stop":1689189538200,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"2db14de36cc6e22f7cde229aad61c276"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa8bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_shopping_cart","uid":"5c3c7b53090c695b","parentUid":"ead87f321c30da81caa15da0dd777a84","status":"broken","time":{"start":1689189538205,"stop":1689189538208,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ead87f321c30da81caa15da0dd777a84"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8be250>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_delete_shopping_cart_not_logged","uid":"771be74d70a70aa0","parentUid":"5a7524cb3f66e6d438038ab0aa92ed10","status":"broken","time":{"start":1689189538213,"stop":1689189538214,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"5a7524cb3f66e6d438038ab0aa92ed10"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_ingredients_list","uid":"c66a99ab60c832d7","parentUid":"c1694e770ea308ec0e82f6e7078cd5f4","status":"broken","time":{"start":1689189538219,"stop":1689189538220,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c1694e770ea308ec0e82f6e7078cd5f4"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8cc7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_ingredient","uid":"a87ca8f3fa122b5b","parentUid":"cd4bf0ed6bd8d684d2f862bddc724ba7","status":"broken","time":{"start":1689189538225,"stop":1689189538226,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"cd4bf0ed6bd8d684d2f862bddc724ba7"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8b6090>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_tags_list","uid":"c6fa8b07053fda58","parentUid":"373ad8aa694a81a5804b3da1fe45f236","status":"broken","time":{"start":1689189538232,"stop":1689189541236,"duration":3004},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"373ad8aa694a81a5804b3da1fe45f236"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8a5b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_tags_not_found","uid":"b247703a3398d40e","parentUid":"43e4d1a4187bb1ad26485d24a57402d6","status":"broken","time":{"start":1689189541243,"stop":1689189544247,"duration":3004},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"43e4d1a4187bb1ad26485d24a57402d6"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}